---
title: "Assignment Week 3: United States Military Academy (USMA) West Point Data"
format: html
editor: visual
---

1\. EITHER save the data sheet as its own CSV file to load in, OR use the read_excel function in the readxl package to read the sheet in directly from the Excel workbook.

```{r}

```

2\. Recreate the femalespeers, malespeers, and totpeople columns **based on the documentation for those columns**, and check whether your calculations match what's in the original data. In other words, look at the excel sheet, read the variable descriptions, and create new variables that fit those descriptions. "Recreate" means "create from scratch." Do *not* use the femalespeers, malespeers, and totpeople columns already in the data to create your new ones. That wouldn't be "recreating", that would be "copying."   (NOTE 1: you won't get an exact match with the old columns, NOTE 2: keep in mind these variables count "peers", i.e. **not including yourself**).

3\. Investigate the rows for which your recreation \*doesn't\* line up exactly with the original columns. Any ideas what the issue might be? Do you trust the original or your recreation more?

4\. Create two new columns from company_n: company, and division. If it's A-1, for example, A is the company, and 1 is the division.

5\. This data follows a certain number of cohorts, which means that in the first year of the data, we only see a small portion of all students, then more the next year, and so on. Limit the data just to years in which you have all four classes present **in full quantity** (i.e. not just a few stragglers but all four entire classes appear to be there. This will entail finding which years those are).

6\. Make the following tables:

a\. Top four companies (A, B, C, etc., not A-1, A-2) with the highest continue_or_grad rates

b\. continue_or_grad rates by class

c\. continue_or_grad rates *of women* by class

Note you can make a table by just creating the appropriate data set and showing it, or by sending it to the knitr::kable() function to get it formatted a little more nicely.

7\. Bonus task (ungraded, tricky): notice anything strange about the "random assignment" of women?
