<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exploratory Data Analysis of Incomes and Expenses for United States Colleges</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="week_4_assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="week_4_assignment_files/libs/quarto-html/quarto.js"></script>
<script src="week_4_assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="week_4_assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="week_4_assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="week_4_assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="week_4_assignment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="week_4_assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="week_4_assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="week_4_assignment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="week_4_assignment_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="week_4_assignment_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploratory Data Analysis of Incomes and Expenses for United States Colleges</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="set-up" class="level3">
<h3 class="anchored" data-anchor-id="set-up">Set Up</h3>
<p>Import data and necessary libraries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: kableExtra

Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'

The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">'./data/college_expenses_and_enrollment.Rdata'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variable-review" class="level3">
<h3 class="anchored" data-anchor-id="variable-review">Variable Review</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>vtable<span class="sc">::</span><span class="fu">vtable</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>df</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Name </th>
   <th style="text-align:left;"> Class </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Values </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> UNITID </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> College ID </td>
   <td style="text-align:left;"> Num: 100654 to 491118 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> STABBR </td>
   <td style="text-align:left;"> factor </td>
   <td style="text-align:left;"> State </td>
   <td style="text-align:left;"> 'AK' 'AL' 'AR' 'AS' 'AZ' and more </td>
  </tr>
  <tr>
   <td style="text-align:left;"> type </td>
   <td style="text-align:left;"> factor </td>
   <td style="text-align:left;"> College Type (NP = Nonprofit) </td>
   <td style="text-align:left;"> 'For-Profit 2-Year' 'For-Profit 4-Year' 'Private NP 2-Year' 'Private NP 4-Year' 'Public 2-Year' and more </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total.Income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Income </td>
   <td style="text-align:left;"> Num: 6067 to 9703300000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total.Expenses </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Expenses </td>
   <td style="text-align:left;"> Num: 4600 to 8629847000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Tuition </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Tuition (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1753736000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Federal </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Federal Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1071432208 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> State </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> State Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 909496000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Local </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Local Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 386724142 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Private </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Private Support (Income) </td>
   <td style="text-align:left;"> Num: -246016 to 1568865000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sales </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Sales (Income) </td>
   <td style="text-align:left;"> Num: -1073664 to 8471746000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Research </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Research (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2910863000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Public.Service </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Public Service (Expense) </td>
   <td style="text-align:left;"> Num: -32 to 807399000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Student.Services </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Student Services (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 284363000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Instruction </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Instruction (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2611938000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Academic.Support </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Academic Support (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 919577000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Other Expenses </td>
   <td style="text-align:left;"> Num: -1 to 5543912000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Institution.Name </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total.Enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 9 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Full.Time.Enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Undergraduate.Enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 103711 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Non-income or expense variables include unique college ID, state abbreviation, college type, institution name, total enrollment, full time enrollment, and undergraduate enrollment. The state and college type factors might be helpful for grouping. The institution name for labeling particular values. Total enrollment is interesting because the minimum value is 9. There was a college with 9 students? Could be an error. A 0 value minimum for full time and undergraduate enrollment makes a little more sense to me, perhaps there are some community colleges, etc. with only part-time students or perhaps college only accepts graduate students, I’m not sure, but also something to investigate. Per the assignment note, most values will indicate the size and the enrollment values can be used to calculate per capita numbers for comparison. It may make the most sense to look at four year schools with full-time undergraduate students for per capita comparisons. I would like to know what year this data set is from. Of note, both college_type and state data type is factor. I think it makes sense to probably change to character.</p>
<p>Income variables include total, tuition, federal support, state support, local support, private support, and sales. I’m assuming income is gross and not net. Some colleges have really low incomes ($6,067?) but I don’t have enough domain knowledge to know if that is reasonable yet. Also what school has a $0 income from tuition? Do they have no students? I’m also not sure why there would be a negative value for private support or sales income. Income might actually be net (revenues - expenses). I attempted to find more information about the variable descriptions via the [IPEDS Survey Components](https://nces.ed.gov/ipeds/use-the-data/survey-components/2/finance) and [IPEDS Compare Institutions Variable Tree](https://nces.ed.gov/ipeds/datacenter/SelectVariables.aspx?stepId=1). To be honest, I’m not quite sure about the data that I’m working with as it was difficult to match variables in the file provided to the site - good real world experience - and I’m going to have to make some assumptions. Biggest call outs so far are (1) finance variables are nested under the type of institution and I’m not quite sure how they are derived in this data set so this may lead to some unexpected variation, (2) there is a difference between Fall Enrollment and 12-Month Enrollment, I’m not quite sure what values are provided in the data set.</p>
<p>Expense variables include total, research, public service, student services, instruction, academic support, and other. There are negative values in public service and other, not sure why yet. I wasn’t sure what all of these categories mean, so using prior links and this [Postsecondary Institution Expenses article](https://nces.ed.gov/programs/coe/indicator/cue/postsecondary-institution-expense#fn6) as best reference. Research is any activity that produces research. Public service is any activity that provides non-instructional services to benefit people outside of the institution (community service, cooperative extension services, public broadcasting services). Student services is any activity that supports student well-being and development outside of formal instruction (admissions, registrar activities, dependent intercollegiate athletics and health services). Instruction is any activity that provides instruction (credit and non-credit), may also include research and public service activities that are not separately budgeted. Academic support is any activity that supports the institution’s mission of instruction, research, and public service. Other expenses is a catch-all for items such as bad debts, income taxes, liability obligations, or other operational expenses not associated with the primary mission of the institution, such as a major federally funded research and development center. The IPEDS Expenses article groups expenses as follows:<br>
1. Independent operations and other<br>
2. Hospital services<br>
3. Net grant aid to students<br>
4. Auxiliary enterprises<br>
5. Academic support, student services, and institutional support<br>
6. Research and public service<br>
7. Instruction</p>
<p>Assuming income means revenue, there is also an IPEDS [Postsecondary Institution Revenues article](https://nces.ed.gov/programs/coe/indicator/cud) to help inform what these columns mean. I get the gist of tuition, federal, state, and local incomes. Private income includes any gifts, grants, and contracts from non-governmental entities. Sales income includes revenues from sales of goods and services such as publications, testing, cosmetology, and hospital. I’m not sure about the data provided, but in the article, private grants and contracts are included in the local income instead of private income. In addition, income is not comparable across types of institutions because they may treat income differently. For example, Pell Grants are usually part of Federal funding for public institutions but usually part of tuition funding for private institutions. The article also groups revenue as follows:<br>
1. Tuition and fees<br>
2. Investments<br>
3. Government<br>
3. Auxiliary enterprises<br>
4. Other</p>
<p>Whew! Lots of questions remaining, but I think I have a better understanding of what some of these variables mean and areas to proceed with caution. And it may make sense to group some of the columns similar to the articles referenced. Also just re-read assignment. The important note uses income interchangeably with revenue, so that question is answered.</p>
</section>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<p>To prepare the data, I renamed the columns for clarification and consistency, then completed the following checks to handle missing values and ensure data seems reasonable. I want to do some initial exploratory data analysis before deciding how to derive per capita values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns and convert state and college type to character.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">college_id =</span> UNITID,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">state =</span> STABBR,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">institution =</span> Institution.Name,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">total_enrollment =</span> Total.Enrollment,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">full_time_enrollment =</span> Full.Time.Enrollment,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">undergraduate_enrollment =</span> Undergraduate.Enrollment,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">college_type =</span> type,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">total_income =</span> Total.Income,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">tuition_income =</span> Tuition,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">federal_income =</span> Federal,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">state_income =</span> State,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">local_income =</span> Local,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">private_income =</span> Private,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">sales_income =</span> Sales,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">total_expense =</span> Total.Expenses,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">research_expense =</span> Research,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">public_service_expense =</span> Public.Service,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_service_expense =</span> Student.Services,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">instruction_expense =</span> Instruction,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">academic_support_expense =</span> Academic.Support,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">other_expense =</span> Other) <span class="sc">%&gt;%</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.factor), as.character))</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Update vtable output to match.</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>vtable<span class="sc">::</span><span class="fu">vtable</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>df</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Name </th>
   <th style="text-align:left;"> Class </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Values </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> college_id </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> College ID </td>
   <td style="text-align:left;"> Num: 100654 to 491118 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> college_type </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Income </td>
   <td style="text-align:left;"> Num: 6067 to 9703300000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Expenses </td>
   <td style="text-align:left;"> Num: 4600 to 8629847000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tuition_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Tuition (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1753736000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> federal_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Federal Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1071432208 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> State Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 909496000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> local_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Local Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 386724142 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> private_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Private Support (Income) </td>
   <td style="text-align:left;"> Num: -246016 to 1568865000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sales_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Sales (Income) </td>
   <td style="text-align:left;"> Num: -1073664 to 8471746000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> research_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Research (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2910863000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> public_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Public Service (Expense) </td>
   <td style="text-align:left;"> Num: -32 to 807399000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> student_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Student Services (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 284363000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instruction_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Instruction (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2611938000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> academic_support_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Academic Support (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 919577000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> other_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Other Expenses </td>
   <td style="text-align:left;"> Num: -1 to 5543912000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> institution </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 9 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> full_time_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> undergraduate_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 103711 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<ol type="1">
<li>Check for missing values and resolve.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize number of missing values per column where they exist.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_if</span>(anyNA, <span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  institution total_enrollment full_time_enrollment undergraduate_enrollment
        &lt;int&gt;            &lt;int&gt;                &lt;int&gt;                    &lt;int&gt;
1         426              516                  516                      516</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are 426 missing institution names and 516 missing values for each enrollment columm. Although it decreases the data set, I can't think of a reasonable reason why an institution would not have a name or any total enrollment so I think it makes sense to remove these rows from the main data set. Since the number of missing values for each enrollment column is the same, I imagine it is the same rows for each column. If not, it is reasonable that a college may not have any full-time students or undergraduate students, or the total enrollment value could be missing due to an error. Check that all missing enrollment values belong to the same rows.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(total_enrollment)) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(total_enrollment,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         full_time_enrollment,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         undergraduate_enrollment) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(<span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  total_enrollment full_time_enrollment undergraduate_enrollment
             &lt;int&gt;                &lt;int&gt;                    &lt;int&gt;
1              516                  516                      516</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirmed. Separate out missing values from main data set. </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>main_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>na_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">is.na</span>(.x)))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reviewing NAs, based on the institution names, many of these are system or district administration offices, so it makes sense to have no enrollment. I still think it makes sense to exclude these institutions because I would like to focus on institutions with students and be able to compare per capita values.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Check that unique values make sense. All values need to be unique for college_id, approximately 50 unique values for state (unless territories are included, if yes, rename column to clarify), and college types need to make sense.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select columns and count unique values.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(college_id, state, college_type) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(<span class="fu">funs</span>(<span class="fu">n_distinct</span>(.)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  college_id state college_type
       &lt;int&gt; &lt;int&gt;        &lt;int&gt;
1       4255    59            6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The number of unique college_id values is equal to the number of observations. There is more than 50 states so reviewing values.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>states_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(state)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reviewing against the IPEDS variable tree, the additional nine values are: District of Columbia (DC), American Samoa (AS), Federated States of Micronesia (FM), Guam (GU), Marshall Islands (MH), Northern Marianas (MP), Palau (PW), Puerto Rico (PR), and the Virgin Islands (VI). Renaming column to clarify</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>main_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">state_or_territory =</span> state)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Review unique college types.</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(college_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  college_type     
  &lt;chr&gt;            
1 Public 4-Year    
2 Private NP 4-Year
3 Public 2-Year    
4 For-Profit 4-Year
5 For-Profit 2-Year
6 Private NP 2-Year</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All college types makes sense (NP = non-profit). Types vary by 2/4 year, public/private, and for/non profit.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>For income and expense values: no negative values, a zero value may also be suspect (a school does not spend any funding on instruction?) but will keep in for now and evaluate during exploratory data analysis. In addition, the sum of income or expense subcategories should not be more than the total.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review income and expense columns with negative observations. I could be missing something, but I don't think it make sense to have negative values in any of these columns.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>vtable<span class="sc">::</span><span class="fu">vtable</span>(main_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>main_df</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Name </th>
   <th style="text-align:left;"> Class </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Values </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> college_id </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> College ID </td>
   <td style="text-align:left;"> Num: 100654 to 489937 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_or_territory </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> college_type </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Income </td>
   <td style="text-align:left;"> Num: 18050 to 9703300000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Expenses </td>
   <td style="text-align:left;"> Num: 4600 to 8629847000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tuition_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Tuition (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1753736000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> federal_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Federal Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1071432208 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> State Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 909496000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> local_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Local Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 386724142 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> private_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Private Support (Income) </td>
   <td style="text-align:left;"> Num: -246016 to 1568865000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sales_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Sales (Income) </td>
   <td style="text-align:left;"> Num: -1073664 to 8471746000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> research_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Research (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2910863000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> public_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Public Service (Expense) </td>
   <td style="text-align:left;"> Num: -32 to 807399000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> student_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Student Services (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 284363000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instruction_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Instruction (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2611938000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> academic_support_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Academic Support (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 919577000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> other_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Other Expenses </td>
   <td style="text-align:left;"> Num: 0 to 5543912000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> institution </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 9 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> full_time_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> undergraduate_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 103711 </td>
  </tr>
</tbody>
</table>

</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are negative values for private_income, sales_income, and public service_expense. Investigate further to better understand and inform next steps.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), <span class="sc">~</span> .x <span class="sc">&lt;</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 21
  college_id state_or_…¹ colle…² total…³ total…⁴ tuiti…⁵ feder…⁶ state…⁷ local…⁸
       &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     176600 MO          Privat…  2.41e6  1.75e6  1.50e6  0            0  0     
2     204662 OH          Public…  1.01e7  8.77e6  4.98e6  2.12e6 3259857  0     
3     206288 OH          Privat…  6.76e6  4.37e6  4.16e6  0            0  0     
4     243665 VI          Public…  6.78e7  4.61e7  1.40e7  2.02e7       0  3.15e7
5     457129 FL          For-Pr…  2.24e7  1.43e7  1.95e7  2.85e6   50619  0     
6     466921 MO          For-Pr…  1.19e7  8.46e6  1.07e7  1.17e6       0  0     
7     482635 TX          For-Pr…  2.67e7  1.72e7  2.42e7  2.19e6       0  0     
8     486433 CA          Privat…  4.32e6  3.92e6  4.29e6  0            0  0     
# … with 12 more variables: private_income &lt;dbl&gt;, sales_income &lt;dbl&gt;,
#   research_expense &lt;dbl&gt;, public_service_expense &lt;dbl&gt;,
#   student_service_expense &lt;dbl&gt;, instruction_expense &lt;dbl&gt;,
#   academic_support_expense &lt;dbl&gt;, other_expense &lt;dbl&gt;, institution &lt;chr&gt;,
#   total_enrollment &lt;dbl&gt;, full_time_enrollment &lt;dbl&gt;,
#   undergraduate_enrollment &lt;dbl&gt;, and abbreviated variable names
#   ¹​state_or_territory, ²​college_type, ³​total_income, ⁴​total_expense, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are only 8 rows with a negative value in any column. It seems like these might be errors. Since it is very few rows, I think it makes more sense to remove rows rather than set to zero or remove the negative sign. </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>neg_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), <span class="sc">~</span> .x <span class="sc">&lt;</span> <span class="dv">0</span>))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>main_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_all</span>(<span class="fu">everything</span>(), <span class="sc">~</span> .x <span class="sc">&gt;=</span> <span class="dv">0</span>))</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for observations where subcategory incomes are greater than the total income. There may be some subcategory incomes not listed (investments?)</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"income"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">calc_income =</span> tuition_income <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>           federal_income <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>           state_income <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>           local_income <span class="sc">+</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>           private_income <span class="sc">+</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>           sales_income,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">income_error =</span> <span class="fu">if_else</span>(total_income <span class="sc">==</span> calc_income, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(income_error <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 9
# … with 9 variables: total_income &lt;dbl&gt;, tuition_income &lt;dbl&gt;,
#   federal_income &lt;dbl&gt;, state_income &lt;dbl&gt;, local_income &lt;dbl&gt;,
#   private_income &lt;dbl&gt;, sales_income &lt;dbl&gt;, calc_income &lt;dbl&gt;,
#   income_error &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No observations where the calculated income is greater than the total income. Check the same for expenses.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"expense"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">calc_expense =</span> research_expense <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>           public_service_expense <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>           student_service_expense <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>           instruction_expense <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>           academic_support_expense <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>           other_expense,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">expense_error =</span> <span class="fu">if_else</span>(total_expense <span class="sc">==</span> calc_expense, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(expense_error <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 9
# … with 9 variables: total_expense &lt;dbl&gt;, research_expense &lt;dbl&gt;,
#   public_service_expense &lt;dbl&gt;, student_service_expense &lt;dbl&gt;,
#   instruction_expense &lt;dbl&gt;, academic_support_expense &lt;dbl&gt;,
#   other_expense &lt;dbl&gt;, calc_expense &lt;dbl&gt;, expense_error &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No expense errors where calculated expense is greater than total expense.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>For enrollment values: apparently some colleges can be really small (see [Deep Springs College, CO](https://en.wikipedia.org/wiki/Deep_Springs_College), so a minimum of 9 might be reasonable, but unlikely. Check that full-time or undergraduate enrollment does not exceed total enrollment. Evaluate outliers during exploratory data analysis.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that enrollment values make sense.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"enrollment"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">full_time_error =</span> <span class="fu">if_else</span>(total_enrollment <span class="sc">&gt;=</span> full_time_enrollment, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">undergrad_error =</span> <span class="fu">if_else</span>(total_enrollment <span class="sc">&gt;=</span> undergraduate_enrollment, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(full_time_error <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> undergrad_error <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 5
# … with 5 variables: total_enrollment &lt;dbl&gt;, full_time_enrollment &lt;dbl&gt;,
#   undergraduate_enrollment &lt;dbl&gt;, full_time_error &lt;dbl&gt;,
#   undergrad_error &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No errors where the number of full-time or undegraduate students is greater than the total enrollment.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis---univariate-non-graphical" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis---univariate-non-graphical">Exploratory Data Analysis - Univariate Non-Graphical</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize main data.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vtable</span>(main_df, <span class="at">lush =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>main_df</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Name </th>
   <th style="text-align:left;"> Class </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Values </th>
   <th style="text-align:left;"> Missing </th>
   <th style="text-align:left;"> Summary </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> college_id </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> College ID </td>
   <td style="text-align:left;"> Num: 100654 to 489937 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 236478.799, sd: 115947.556, nuniq: 4247 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_or_territory </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> 'AK' 'AL' 'AR' 'AS' 'AZ' and more </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> nuniq: 58 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> college_type </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> 'For-Profit 2-Year' 'For-Profit 4-Year' 'Private NP 2-Year' 'Private NP 4-Year' 'Public 2-Year' and more </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> nuniq: 6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Income </td>
   <td style="text-align:left;"> Num: 18050 to 9703300000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 138655411.431, sd: 516219025.033, nuniq: 4246 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Total Expenses </td>
   <td style="text-align:left;"> Num: 4600 to 8629847000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 112065573.219, sd: 455608837.601, nuniq: 4246 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tuition_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Tuition (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1753736000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 39200702.177, sd: 103705562.736, nuniq: 4234 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> federal_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Federal Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1071432208 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 13603676.915, sd: 49842601.062, nuniq: 4006 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> State Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 909496000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 19424969.575, sd: 57695385.876, nuniq: 3254 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> local_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Local Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 386724142 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 3561745.404, sd: 15046169.894, nuniq: 1385 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> private_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Private Support (Income) </td>
   <td style="text-align:left;"> Num: 0 to 1568865000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 11381225.554, sd: 65123488.129, nuniq: 2940 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sales_income </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Sales (Income) </td>
   <td style="text-align:left;"> Num: 0 to 8471746000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 51483091.805, sd: 338979649.898, nuniq: 2469 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> research_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Research (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2910863000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 13707702.315, sd: 91623473.923, nuniq: 1218 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> public_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Public Service (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 807399000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 4237676.133, sd: 29417237.05, nuniq: 1781 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> student_service_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Student Services (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 284363000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 9461677.462, sd: 19834217.46, nuniq: 4134 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instruction_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Instruction (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 2611938000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 41744639.11, sd: 131670070.937, nuniq: 4243 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> academic_support_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Academic Support (Expense) </td>
   <td style="text-align:left;"> Num: 0 to 919577000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 11316116.537, sd: 41080121.988, nuniq: 4025 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> other_expense </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Other Expenses </td>
   <td style="text-align:left;"> Num: 0 to 5543912000 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 31597761.663, sd: 229751475.632, nuniq: 2272 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> institution </td>
   <td style="text-align:left;"> character </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> 'A T Still University of Health Sciences' 'Aaniiih Nakoda College' 'Abilene Christian University' 'Abraham Baldwin Agricultural College' 'Abraham Lincoln University' and more </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> nuniq: 4193 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 9 to 131629 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 4653.471, sd: 8338.502, nuniq: 2938 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> full_time_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 131629 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 2854.92, sd: 5906.611, nuniq: 2593 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> undergraduate_enrollment </td>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> NULL </td>
   <td style="text-align:left;"> Num: 0 to 103711 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> mean: 3961.796, sd: 6985.491, nuniq: 2806 </td>
  </tr>
</tbody>
</table>

</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sumtable</span>(main_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Summary Statistics</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> Std. Dev. </th>
   <th style="text-align:left;"> Min </th>
   <th style="text-align:left;"> Pctl. 25 </th>
   <th style="text-align:left;"> Pctl. 75 </th>
   <th style="text-align:left;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> college_id </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 236478.799 </td>
   <td style="text-align:left;"> 115947.556 </td>
   <td style="text-align:left;"> 100654 </td>
   <td style="text-align:left;"> 155918.5 </td>
   <td style="text-align:left;"> 239500 </td>
   <td style="text-align:left;"> 489937 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> college_type </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... For-Profit 2-Year </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 13.4% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... For-Profit 4-Year </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 7.2% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... Private NP 2-Year </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 3.2% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... Private NP 4-Year </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 36.5% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... Public 2-Year </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 22.7% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ... Public 4-Year </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 17% </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 138655411.431 </td>
   <td style="text-align:left;"> 516219025.033 </td>
   <td style="text-align:left;"> 18050 </td>
   <td style="text-align:left;"> 7471370.5 </td>
   <td style="text-align:left;"> 83185270 </td>
   <td style="text-align:left;"> 9703300000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 112065573.219 </td>
   <td style="text-align:left;"> 455608837.601 </td>
   <td style="text-align:left;"> 4600 </td>
   <td style="text-align:left;"> 4111088 </td>
   <td style="text-align:left;"> 57246570.5 </td>
   <td style="text-align:left;"> 8629847000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tuition_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 39200702.177 </td>
   <td style="text-align:left;"> 103705562.736 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 2566536.5 </td>
   <td style="text-align:left;"> 30290751 </td>
   <td style="text-align:left;"> 1753736000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> federal_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 13603676.915 </td>
   <td style="text-align:left;"> 49842601.062 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 815985.5 </td>
   <td style="text-align:left;"> 9014613 </td>
   <td style="text-align:left;"> 1071432208 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 19424969.575 </td>
   <td style="text-align:left;"> 57695385.876 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 7361.5 </td>
   <td style="text-align:left;"> 13681910.5 </td>
   <td style="text-align:left;"> 909496000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> local_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 3561745.404 </td>
   <td style="text-align:left;"> 15046169.894 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 135102 </td>
   <td style="text-align:left;"> 386724142 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> private_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 11381225.554 </td>
   <td style="text-align:left;"> 65123488.129 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 3685137.5 </td>
   <td style="text-align:left;"> 1568865000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sales_income </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 51483091.805 </td>
   <td style="text-align:left;"> 338979649.898 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 11272013.5 </td>
   <td style="text-align:left;"> 8471746000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> research_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 13707702.315 </td>
   <td style="text-align:left;"> 91623473.923 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 58604 </td>
   <td style="text-align:left;"> 2910863000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> public_service_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 4237676.133 </td>
   <td style="text-align:left;"> 29417237.05 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 579875 </td>
   <td style="text-align:left;"> 807399000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> student_service_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 9461677.462 </td>
   <td style="text-align:left;"> 19834217.46 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 691238.5 </td>
   <td style="text-align:left;"> 10112706.5 </td>
   <td style="text-align:left;"> 284363000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instruction_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 41744639.11 </td>
   <td style="text-align:left;"> 131670070.937 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 2191642 </td>
   <td style="text-align:left;"> 31016053 </td>
   <td style="text-align:left;"> 2611938000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> academic_support_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 11316116.537 </td>
   <td style="text-align:left;"> 41080121.988 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 442338 </td>
   <td style="text-align:left;"> 6932937 </td>
   <td style="text-align:left;"> 919577000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> other_expense </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 31597761.663 </td>
   <td style="text-align:left;"> 229751475.632 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 6784030 </td>
   <td style="text-align:left;"> 5543912000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_enrollment </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 4653.471 </td>
   <td style="text-align:left;"> 8338.502 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 365.5 </td>
   <td style="text-align:left;"> 5007.5 </td>
   <td style="text-align:left;"> 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> full_time_enrollment </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 2854.92 </td>
   <td style="text-align:left;"> 5906.611 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 264 </td>
   <td style="text-align:left;"> 2705.5 </td>
   <td style="text-align:left;"> 131629 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> undergraduate_enrollment </td>
   <td style="text-align:left;"> 4247 </td>
   <td style="text-align:left;"> 3961.796 </td>
   <td style="text-align:left;"> 6985.491 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 279.5 </td>
   <td style="text-align:left;"> 4322 </td>
   <td style="text-align:left;"> 103711 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>No missing values, as expected. There is one state or territory that is no longer represented. Will look at graphs for clearer picture of income and expense values. Percentage breakdown of college types is interesting. The majority of colleges are private non-profit 4-year schools (36.5%), followed by public 2-year (22.7%), public 4-year (17%), for-profit 2-year (13.4%), for-profit 4-year (7.2%), and lastly private non-profit 2-year (3.2%). Missed earlier that not all the institution names are unique. I’m guessing there might be multiple institutions with the same name, sub-entities, or duplicates. Need to further investigate and potentially remove.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review duplicate institutions</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>duplicates_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(institution) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(institution)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for any exact matches.</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>duplicates_df <span class="sc">%&gt;%</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by_all</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 21
# … with 21 variables: college_id &lt;dbl&gt;, state_or_territory &lt;chr&gt;,
#   college_type &lt;chr&gt;, total_income &lt;dbl&gt;, total_expense &lt;dbl&gt;,
#   tuition_income &lt;dbl&gt;, federal_income &lt;dbl&gt;, state_income &lt;dbl&gt;,
#   local_income &lt;dbl&gt;, private_income &lt;dbl&gt;, sales_income &lt;dbl&gt;,
#   research_expense &lt;dbl&gt;, public_service_expense &lt;dbl&gt;,
#   student_service_expense &lt;dbl&gt;, instruction_expense &lt;dbl&gt;,
#   academic_support_expense &lt;dbl&gt;, other_expense &lt;dbl&gt;, institution &lt;chr&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are no exact row matches.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Duplicate institution names are due to several reasons. I also reviewed the definition of UNITID (college_id). It is “Unique identification number assigned to postsecondary institutions surveyed through the Integrated Postsecondary Education Data System (IPEDS). Also referred to as UNITID or IPEDS ID.” The main ones seem to be as follows:</p>
<ol type="1">
<li>Each campus belonging to the institution has a unique college ID. For example Academy of Interactive Entertainment has a unique ID for their Washington state campus and Louisiana campus. It may be in the same state as well, such as American College of Healthcare and Technology with two California campuses.</li>
<li>There are separate institutions with the same name, such as the two Anderson colleges.</li>
</ol>
<p>I decided to leave in duplicate names and continue using the college_id as the identifier. I think it is likely some separate college campuses are essentially separate, if affiliate institutions.</p>
</section>
<section id="exploratory-data-analysis---univariate-graphical" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis---univariate-graphical">Exploratory Data Analysis - Univariate Graphical</h3>
<p>First, look at the distributions for continuous variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create list of continuous target variables.</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>target_variables <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"income|expense|enrollment"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>()</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize historgrams of target variables.</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> target_variables) {</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">ggplot</span>(main_df, <span class="fu">aes_string</span>(variable)) <span class="sc">+</span> </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_histogram</span>())</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation ideoms with `aes()`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-8.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-9.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-10.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-11.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-12.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-13.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-14.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-15.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-16.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-10-17.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>All continuous variables are heavily skewed right. To me, this mostly makes sense. It’s less likely to have colleges with high sources of income, expenses, or enrollments.</p>
<p>Second, look at the distribution of categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># college type</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(main_df) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> college_type, <span class="at">y =</span> <span class="fu">after_stat</span>(count<span class="sc">/</span><span class="fu">sum</span>(count)))) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"percentage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># state or territory</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(main_df) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> state_or_territory, <span class="at">y =</span> <span class="fu">after_stat</span>(count<span class="sc">/</span><span class="fu">sum</span>(count)))) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"percentage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I wonder why the private non-profit 4-year colleges have the highest number of schools and the private non-profit 2-year colleges have the lowest number of schools. This is also a flipped relationship compared to for-profit and public schools where there are more 2-year colleges than 4-year colleges. Per the articles mentioned prior, may make sense to group by public, private for-profit, and private non-profit. In hindsight, that’s probably why the variable was original a 2x3 factor. The state_or_territory distribution is squished, but California clearly has the highest percentage of institutions. It may make sense to summarize by [region](https://nces.ed.gov/ipeds/Search/ViewTable?tableId=10788#:~:text=Utah%2C%20and%20Wyoming.-,The%20Far%20West%20region%20includes%20Alaska%2C%20California%2C%20Hawaii%2C,Nevada%2C%20Oregon%2C%20and%20Washington.).</p>
</section>
<section id="exploratory-data-analysis---multivariate-non-graphical" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis---multivariate-non-graphical">Exploratory Data Analysis - Multivariate Non-Graphical</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by college_type</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>main_df <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sumtable</span>(<span class="at">group =</span> <span class="st">'college_type'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Summary Statistics</caption>
 <thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">college_type</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">For-Profit 2-Year</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">For-Profit 4-Year</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Private NP 2-Year</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Private NP 4-Year</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Public 2-Year</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Public 4-Year</div></th>
</tr>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
   <th style="text-align:left;"> N </th>
   <th style="text-align:left;"> Mean </th>
   <th style="text-align:left;"> SD </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> college_id </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 336746.66 </td>
   <td style="text-align:left;"> 134307.434 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 358338.859 </td>
   <td style="text-align:left;"> 137249.749 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 281980.19 </td>
   <td style="text-align:left;"> 128363.168 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 214597.433 </td>
   <td style="text-align:left;"> 97399.714 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 199875.013 </td>
   <td style="text-align:left;"> 83954.201 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 193224.418 </td>
   <td style="text-align:left;"> 69418.249 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 7014834.067 </td>
   <td style="text-align:left;"> 11273644.914 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 43295808.214 </td>
   <td style="text-align:left;"> 124444646.5 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 7187566.285 </td>
   <td style="text-align:left;"> 31989186.812 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 148533554.001 </td>
   <td style="text-align:left;"> 584089632.796 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 50083211.346 </td>
   <td style="text-align:left;"> 57035618.53 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 404733005.837 </td>
   <td style="text-align:left;"> 850184734.313 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 3096931.07 </td>
   <td style="text-align:left;"> 4787196.931 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 22232996.451 </td>
   <td style="text-align:left;"> 59827856.798 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 4465422.591 </td>
   <td style="text-align:left;"> 17182568.523 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 109892122.412 </td>
   <td style="text-align:left;"> 485730980.804 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 34904140.041 </td>
   <td style="text-align:left;"> 40537913.213 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 364025296.673 </td>
   <td style="text-align:left;"> 790731215.274 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tuition_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 4976998.9 </td>
   <td style="text-align:left;"> 7329286.146 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 34191341.069 </td>
   <td style="text-align:left;"> 99208785.557 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 5053602.635 </td>
   <td style="text-align:left;"> 23985215.581 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 47374899.449 </td>
   <td style="text-align:left;"> 110394619.456 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 9542394.291 </td>
   <td style="text-align:left;"> 12884329.172 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 96858752.472 </td>
   <td style="text-align:left;"> 163821276.351 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> federal_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 1897514.93 </td>
   <td style="text-align:left;"> 4237712.025 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 6921177.836 </td>
   <td style="text-align:left;"> 23057169.709 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 1491211.912 </td>
   <td style="text-align:left;"> 8007400.845 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 3663780.426 </td>
   <td style="text-align:left;"> 10679253.892 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 10202183.148 </td>
   <td style="text-align:left;"> 11004250.736 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 53838135.789 </td>
   <td style="text-align:left;"> 109405891.255 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> state_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 118650.239 </td>
   <td style="text-align:left;"> 491578.982 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 413592.796 </td>
   <td style="text-align:left;"> 1365046.627 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 218213.007 </td>
   <td style="text-align:left;"> 537674.843 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 1748802.55 </td>
   <td style="text-align:left;"> 3652930.231 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 18065691.604 </td>
   <td style="text-align:left;"> 21306011.371 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 86078417.035 </td>
   <td style="text-align:left;"> 115442704.831 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> local_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 17603.56 </td>
   <td style="text-align:left;"> 135198.651 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 8922.089 </td>
   <td style="text-align:left;"> 49010.327 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 10522.109 </td>
   <td style="text-align:left;"> 39369.312 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 361612.562 </td>
   <td style="text-align:left;"> 6052041.611 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 11736762.54 </td>
   <td style="text-align:left;"> 22186514.476 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 4484496.258 </td>
   <td style="text-align:left;"> 21614033.291 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> private_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 4066.439 </td>
   <td style="text-align:left;"> 43608.51 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 36222.891 </td>
   <td style="text-align:left;"> 554679.555 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 414016.62 </td>
   <td style="text-align:left;"> 1509397.761 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 18409548.077 </td>
   <td style="text-align:left;"> 91795266.749 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 536178.489 </td>
   <td style="text-align:left;"> 1315521.282 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 26612658.506 </td>
   <td style="text-align:left;"> 78705049.431 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sales_income </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 1724551.533 </td>
   <td style="text-align:left;"> 9550712.639 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 76974910.937 </td>
   <td style="text-align:left;"> 434834766.253 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 1.274 </td>
   <td style="text-align:left;"> 39.551 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 136860545.777 </td>
   <td style="text-align:left;"> 504528250.165 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> research_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 1113.491 </td>
   <td style="text-align:left;"> 9846.481 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 15467.329 </td>
   <td style="text-align:left;"> 109317.052 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 8469.825 </td>
   <td style="text-align:left;"> 94794.652 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 13696937.245 </td>
   <td style="text-align:left;"> 112470154.112 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 30628.428 </td>
   <td style="text-align:left;"> 159860.323 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 51177750.792 </td>
   <td style="text-align:left;"> 142625519.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> public_service_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 4696.123 </td>
   <td style="text-align:left;"> 44357.19 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 33062.02 </td>
   <td style="text-align:left;"> 207519.4 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 10381.19 </td>
   <td style="text-align:left;"> 83622.587 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 1846880.145 </td>
   <td style="text-align:left;"> 20622624.789 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 791103.768 </td>
   <td style="text-align:left;"> 1838345.81 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 19886388.384 </td>
   <td style="text-align:left;"> 62286280.397 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> student_service_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 821168.93 </td>
   <td style="text-align:left;"> 1764164.29 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 6612360.957 </td>
   <td style="text-align:left;"> 24646874.442 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 1586320.73 </td>
   <td style="text-align:left;"> 10473639.846 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 10681689.337 </td>
   <td style="text-align:left;"> 22387185.934 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 6064728.89 </td>
   <td style="text-align:left;"> 7175685.921 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 20893597.087 </td>
   <td style="text-align:left;"> 25865772.185 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> instruction_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 1748657.337 </td>
   <td style="text-align:left;"> 2491880.888 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 8593162.526 </td>
   <td style="text-align:left;"> 20838310.851 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 2161070.781 </td>
   <td style="text-align:left;"> 4446681.75 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 39996314.935 </td>
   <td style="text-align:left;"> 157094954.196 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 23236839.668 </td>
   <td style="text-align:left;"> 27229338.14 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 123254512.361 </td>
   <td style="text-align:left;"> 196858987.53 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> academic_support_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 521295.189 </td>
   <td style="text-align:left;"> 1211590.045 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 3849726.224 </td>
   <td style="text-align:left;"> 12203277.675 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 699180.066 </td>
   <td style="text-align:left;"> 2741354.816 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 10365247.95 </td>
   <td style="text-align:left;"> 44384446.988 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 4780839.287 </td>
   <td style="text-align:left;"> 6726133.351 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 35763768.472 </td>
   <td style="text-align:left;"> 69178755.614 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> other_expense </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 3129217.395 </td>
   <td style="text-align:left;"> 11757560.221 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 33305052.801 </td>
   <td style="text-align:left;"> 252539517.755 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 113049279.576 </td>
   <td style="text-align:left;"> 405557382.948 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> total_enrollment </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 360.928 </td>
   <td style="text-align:left;"> 627.082 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 2850.237 </td>
   <td style="text-align:left;"> 10457.305 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 245.423 </td>
   <td style="text-align:left;"> 286.48 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 2647.365 </td>
   <td style="text-align:left;"> 5414.006 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 6031.59 </td>
   <td style="text-align:left;"> 7287.443 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 12104.706 </td>
   <td style="text-align:left;"> 11952.515 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> full_time_enrollment </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 330.218 </td>
   <td style="text-align:left;"> 612.859 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 1660.237 </td>
   <td style="text-align:left;"> 8271.544 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 188.869 </td>
   <td style="text-align:left;"> 228.919 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 1985.726 </td>
   <td style="text-align:left;"> 3990.713 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 2171.709 </td>
   <td style="text-align:left;"> 2431.847 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 8635.227 </td>
   <td style="text-align:left;"> 9570.064 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> undergraduate_enrollment </td>
   <td style="text-align:left;"> 570 </td>
   <td style="text-align:left;"> 360.928 </td>
   <td style="text-align:left;"> 627.082 </td>
   <td style="text-align:left;"> 304 </td>
   <td style="text-align:left;"> 2041.474 </td>
   <td style="text-align:left;"> 7553.769 </td>
   <td style="text-align:left;"> 137 </td>
   <td style="text-align:left;"> 245.423 </td>
   <td style="text-align:left;"> 286.48 </td>
   <td style="text-align:left;"> 1550 </td>
   <td style="text-align:left;"> 1831.832 </td>
   <td style="text-align:left;"> 3738.214 </td>
   <td style="text-align:left;"> 964 </td>
   <td style="text-align:left;"> 6031.59 </td>
   <td style="text-align:left;"> 7287.443 </td>
   <td style="text-align:left;"> 722 </td>
   <td style="text-align:left;"> 10127.418 </td>
   <td style="text-align:left;"> 9702.082 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Enrollment highly varies by college_type. For example, the for-profit 2-year program has fairly close average total, undergraduate, and full-time enrollments. On average, there is 360 students per program, all of which are undergraduate and most are full time. Compare these data to the public 4-year program where the average total enrollment is 12,140 students per program, however, the average number full-time students is 8,635 per program, and 10,127 students on average are undergraduates. Standard deviations are very high for all categories, so I think this is where college size comes into play and calculating per capita values are important.</p>
</section>
<section id="exploratory-data-analysis---multivariate-graphical" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis---multivariate-graphical">Exploratory Data Analysis - Multivariate Graphical</h3>
<p>There’s a lot of directions to go with exploratory data analysis. I found the IPEDS visuals from the articles linked earlier inspiring, so I would like to explore something similar. Reviewing, it sounds like “per capita” is calculated as per full-time student plus part-time equivalent. I think it makes the most sense to follow a similar calculation - I don’t know if graduate versus undergraduate tuition costs are that different, or at least I think full-time versus part-time is more important. In addition this “per capita” calculation, I decided to group the college types and financial categories. Due to time constraints, I focused on income.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate financial values per full time equivalent (FTE) student. Assuming that a part-time student exactly half of a full-time student, and rounding up to provide a more conservative estimate.</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>per_cap_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">government_income =</span> federal_income <span class="sc">+</span> state_income <span class="sc">+</span> local_income,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">other_income =</span> private_income <span class="sc">+</span> sales_income,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">re_pub_serv_expense =</span> research_expense <span class="sc">+</span> public_service_expense,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">stu_ser_aca_sup_expense =</span> student_service_expense <span class="sc">+</span> academic_support_expense,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fte =</span> <span class="fu">round</span>(</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>    full_time_enrollment <span class="sc">+</span> ((total_enrollment <span class="sc">-</span> full_time_enrollment) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>),</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>((<span class="fu">contains</span>(<span class="st">"income"</span>) <span class="sc">|</span> <span class="fu">contains</span>(<span class="st">"expense"</span>)),  <span class="sc">~</span> .x <span class="sc">/</span> fte),</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">program_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"For-Profit"</span>, college_type) <span class="sc">~</span> <span class="st">"Private for-profit"</span>,</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Private NP"</span>, college_type) <span class="sc">~</span> <span class="st">"Private nonprofit"</span>,</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Public"</span>, college_type) <span class="sc">~</span> <span class="st">"Public"</span>,</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Error"</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">program_year =</span> <span class="fu">case_when</span>(<span class="fu">grepl</span>(<span class="st">"2-Year"</span>, college_type) <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">grepl</span>(<span class="st">"4-Year"</span>, college_type) <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>                             <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>)</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if situations where income does not add up as test. This was happening due to slight differences with how floating point numbers are calculated, numbers are the same (see work below).</span></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>per_cap_df <span class="sc">%&gt;%</span></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"income"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">calc_income_1 =</span> tuition_income <span class="sc">+</span></span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>           federal_income <span class="sc">+</span></span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>           state_income <span class="sc">+</span></span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>           local_income <span class="sc">+</span></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>           private_income <span class="sc">+</span></span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>           sales_income,</span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a>         <span class="at">calc_income_2 =</span> (tuition_income <span class="sc">+</span> </span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a>                          government_income <span class="sc">+</span></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a>                          other_income),</span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a>         <span class="at">income_error_1 =</span> <span class="fu">if_else</span>(</span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(total_income, <span class="dv">0</span>) <span class="sc">==</span> <span class="fu">round</span>(calc_income_1, <span class="dv">0</span>), <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a>         <span class="at">income_error_2 =</span> <span class="fu">if_else</span>(</span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(total_income, <span class="dv">0</span>) <span class="sc">==</span> <span class="fu">round</span>(calc_income_2, <span class="dv">0</span>), <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(total_income, calc_income_1, calc_income_2, income_error_1, income_error_2) <span class="sc">%&gt;%</span></span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>((income_error_1 <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|</span> (income_error_2 <span class="sc">==</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 5
# … with 5 variables: total_income &lt;dbl&gt;, calc_income_1 &lt;dbl&gt;,
#   calc_income_2 &lt;dbl&gt;, income_error_1 &lt;dbl&gt;, income_error_2 &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Review high-level financial graphs by program type. Note: Tried additional variables but too crowded.</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>fin_df <span class="ot">&lt;-</span> per_cap_df <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(program_type,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>         total_income,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>         total_expense)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(fin_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare income graph. Pivot to long form to get funding source category.</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>income_df <span class="ot">&lt;-</span> per_cap_df <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(program_type, tuition_income, government_income, other_income) <span class="sc">%&gt;%</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">ends_with</span>(<span class="st">"income"</span>), <span class="at">names_to =</span> <span class="st">"income_source"</span>, <span class="at">values_to =</span> <span class="st">"amount"</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>income_df <span class="ot">&lt;-</span> income_df <span class="sc">%&gt;%</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type, income_source) <span class="sc">%&gt;%</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_amount =</span> <span class="fu">sum</span>(amount)) <span class="sc">%&gt;%</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> total_amount <span class="sc">/</span> <span class="fu">sum</span>(total_amount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'program_type'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<p>Graph percent distribution of total income by control of institution and funding source.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data.</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>income_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">government_income =</span> federal_income <span class="sc">+</span> state_income <span class="sc">+</span> local_income,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">other_income =</span> private_income <span class="sc">+</span> sales_income,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">program_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">grepl</span>(<span class="st">"For-Profit"</span>, college_type) <span class="sc">~</span> <span class="st">"Private for-profit"</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">grepl</span>(<span class="st">"Private NP"</span>, college_type) <span class="sc">~</span> <span class="st">"Private nonprofit"</span>,</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">grepl</span>(<span class="st">"Public"</span>, college_type) <span class="sc">~</span> <span class="st">"Public"</span>,</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>           <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Error"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(program_type, tuition_income, government_income, other_income) <span class="sc">%&gt;%</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">ends_with</span>(<span class="st">"income"</span>), <span class="at">names_to =</span> <span class="st">"source"</span>, <span class="at">values_to =</span> <span class="st">"amount"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type, source) <span class="sc">%&gt;%</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_amount =</span> <span class="fu">sum</span>(amount)) <span class="sc">%&gt;%</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> total_amount <span class="sc">/</span> <span class="fu">sum</span>(total_amount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'program_type'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph.</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(income_df, <span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> total_amount, <span class="at">fill =</span> source)) <span class="sc">+</span> </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">sprintf</span>(<span class="st">"%1.1f"</span>, percent<span class="sc">*</span><span class="dv">100</span>),<span class="st">"%"</span>)),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">position=</span><span class="fu">position_fill</span>(<span class="at">vjust=</span><span class="fl">0.5</span>), <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Percent Distribution of Total Income </span><span class="sc">\n</span><span class="st">by Control of Institution and Funding Source"</span>) <span class="sc">+</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Control of Institution"</span>) <span class="sc">+</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"Percent of Income"</span>) <span class="sc">+</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">name =</span> <span class="st">"Funding Source"</span>,</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Government"</span>, <span class="st">"Private and Sales"</span>, <span class="st">"Tuition and Fees"</span>)) <span class="sc">+</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Keeping in mind that funding for different institutional controls cannot be compared because they label funding sources differently…</p>
<p>Over three-fourths of private for-profit funding is from tuition and fees with almost a fifth from the government and only a little from private and sales. Two-thirds of private nonprofit funding is from private and sales sources, less than one-third is from tuition and fees, and only a little from the government. Funding for public institutions is approximately two-fifths from government sources, one-third from private and sales sources, and less than one-fourth from tuition and fees. I think this is helpful to see where funding comes from for each type of institutional control.</p>
<p>Graph tuition and fee income per full-time equivalent student by control of institution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data. </span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>tuition_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tuition_income, total_enrollment, college_type, full_time_enrollment) <span class="sc">%&gt;%</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fte =</span> <span class="fu">round</span>(</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    full_time_enrollment <span class="sc">+</span> ((total_enrollment <span class="sc">-</span> full_time_enrollment) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>),</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">tuition_per_fte =</span> (tuition_income <span class="sc">/</span> fte),</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">program_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"For-Profit"</span>, college_type) <span class="sc">~</span> <span class="st">"Private for-profit"</span>,</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Private NP"</span>, college_type) <span class="sc">~</span> <span class="st">"Private nonprofit"</span>,</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Public"</span>, college_type) <span class="sc">~</span> <span class="st">"Public"</span>,</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Error"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tuition_per_fte, program_type)</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure out color.</span></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"RColorBrewer"</span>)</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a><span class="fu">display.brewer.pal</span>(<span class="dv">9</span>, <span class="st">"Blues"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">brewer.pal</span>(<span class="dv">9</span>, <span class="st">"Blues"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "#F7FBFF" "#DEEBF7" "#C6DBEF" "#9ECAE1" "#6BAED6" "#4292C6" "#2171B5"
[8] "#08519C" "#08306B"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check shape of tuition per full-time equivalent student to see if it makes sense to take mean or median.</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tuition_df, <span class="fu">aes</span>(tuition_per_fte)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data is heavily skewed right, so using the median to determine average tuition per full time equivalent student by control of institution.</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>tuition_df <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_per_fte =</span> <span class="fu">median</span>(tuition_per_fte)) <span class="sc">%&gt;%</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte), <span class="at">fill =</span> <span class="st">"#4292C6"</span>) <span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tuition and Fees Income per Full-Time Equivalent (FTE) Student </span><span class="sc">\n</span><span class="st"> by Control of Institution"</span>,</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"(Averaged by Median)"</span>) <span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Control of Institution"</span>) <span class="sc">+</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"Tuition and Fees Income"</span>) <span class="sc">+</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte, <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">round</span>(median_per_fte, <span class="dv">0</span>))),</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>() <span class="sc">+</span></span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The average tuition and fees per full-time equivalent student is highest for private nonprofits, closely followed by private for-profits, and much lower for public institutions. This may be because private institutions treat some government funding as tuition income.</p>
<p>Graph government income per full-time equivalent student by funding source and control of the institution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data. </span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>gov_df <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(federal_income, state_income, local_income, total_enrollment, college_type, full_time_enrollment) <span class="sc">%&gt;%</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fte =</span> <span class="fu">round</span>(</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    full_time_enrollment <span class="sc">+</span> ((total_enrollment <span class="sc">-</span> full_time_enrollment) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>),</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">contains</span>(<span class="st">"income"</span>),  <span class="sc">~</span> .x <span class="sc">/</span> fte),</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">program_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"For-Profit"</span>, college_type) <span class="sc">~</span> <span class="st">"Private for-profit"</span>,</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Private NP"</span>, college_type) <span class="sc">~</span> <span class="st">"Private nonprofit"</span>,</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Public"</span>, college_type) <span class="sc">~</span> <span class="st">"Public"</span>,</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Error"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(federal_income, state_income, local_income, program_type) <span class="sc">%&gt;%</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state_and_local_income =</span> state_income <span class="sc">+</span> local_income)</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Check shape of government incomes per full-time equivalent student to see if it makes sense to take mean or median.</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>gov_df <span class="sc">%&gt;%</span></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(program_type <span class="sc">==</span> <span class="st">"Private nonprofit"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> federal_income)) <span class="sc">+</span></span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create list of government income variables.</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>gov_variables <span class="ot">&lt;-</span> gov_df <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"income"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>()</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize historgrams of target variables.</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> gov_variables) {</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">ggplot</span>(gov_df, <span class="fu">aes_string</span>(variable)) <span class="sc">+</span> </span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_histogram</span>())</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(gov_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-6.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Played around with different program_types and I think it still makes sense to take the median.Most data is heavily skewed right.</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>fed_plot <span class="ot">&lt;-</span> gov_df <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_per_fte =</span> <span class="fu">median</span>(federal_income)) <span class="sc">%&gt;%</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte), <span class="at">fill =</span> <span class="st">"#4292C6"</span>) <span class="sc">+</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Federal Income per Full-Time Equivalent (FTE) Student </span><span class="sc">\n</span><span class="st"> by Control of Institution"</span>,</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"(Averaged by Median)"</span>) <span class="sc">+</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Control of Institution"</span>) <span class="sc">+</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"Federal Income"</span>) <span class="sc">+</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte, <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">round</span>(median_per_fte, <span class="dv">0</span>))),</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb85-14"><a href="#cb85-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb85-15"><a href="#cb85-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb85-16"><a href="#cb85-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-17"><a href="#cb85-17" aria-hidden="true" tabindex="-1"></a>state_and_local_plot <span class="ot">&lt;-</span> gov_df <span class="sc">%&gt;%</span></span>
<span id="cb85-18"><a href="#cb85-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb85-19"><a href="#cb85-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_per_fte =</span> <span class="fu">median</span>(state_and_local_income)) <span class="sc">%&gt;%</span></span>
<span id="cb85-20"><a href="#cb85-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb85-21"><a href="#cb85-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte), <span class="at">fill =</span> <span class="st">"#4292C6"</span>) <span class="sc">+</span></span>
<span id="cb85-22"><a href="#cb85-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"State and Local Income per Full-Time Equivalent (FTE) Student </span><span class="sc">\n</span><span class="st"> by Control of Institution"</span>,</span>
<span id="cb85-23"><a href="#cb85-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"(Averaged by Median)"</span>) <span class="sc">+</span></span>
<span id="cb85-24"><a href="#cb85-24" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Control of Institution"</span>) <span class="sc">+</span></span>
<span id="cb85-25"><a href="#cb85-25" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"State and Local Income"</span>) <span class="sc">+</span></span>
<span id="cb85-26"><a href="#cb85-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, <span class="at">y =</span> median_per_fte, <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">round</span>(median_per_fte, <span class="dv">0</span>))),</span>
<span id="cb85-27"><a href="#cb85-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb85-28"><a href="#cb85-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb85-29"><a href="#cb85-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb85-30"><a href="#cb85-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb85-31"><a href="#cb85-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-32"><a href="#cb85-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(fed_plot, state_and_local_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-7.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After playing around with different libraries, I think it may work best to redo graphs with a facet grid.</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>gov_df <span class="sc">%&gt;%</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_fed =</span> <span class="fu">median</span>(federal_income), </span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_state_local =</span> <span class="fu">median</span>(state_and_local_income)) <span class="sc">%&gt;%</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">contains</span>(<span class="st">"avg"</span>), <span class="at">names_to =</span> <span class="st">"source"</span>, <span class="at">values_to =</span> <span class="st">"avg_amount"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">source =</span> <span class="fu">case_when</span>(source <span class="sc">==</span> <span class="st">"avg_fed"</span> <span class="sc">~</span> <span class="st">"Federal"</span>,</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>                            source <span class="sc">==</span> <span class="st">"avg_state_local"</span> <span class="sc">~</span> <span class="st">"State and Local"</span>,</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>                            <span class="cn">TRUE</span> <span class="sc">~</span> source)) <span class="sc">%&gt;%</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(program_type, avg_amount)) <span class="sc">+</span></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#4292C6"</span>) <span class="sc">+</span></span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Government Income per Full-Time Equivalent (FTE) Student </span><span class="sc">\n</span><span class="st">by Control of Institution"</span>,</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"(Averaged by Median)"</span>) <span class="sc">+</span></span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Control of Institution"</span>) <span class="sc">+</span></span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"Income"</span>) <span class="sc">+</span></span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> program_type, </span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> avg_amount, </span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>                <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">round</span>(avg_amount, <span class="dv">0</span>))),</span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"#333333"</span>,</span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>,</span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(source)) <span class="sc">+</span></span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-16-8.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Public institutions get the most government funding per student with significantly more state and local than federal funding. All institutions receive some type of federal funding, but private for-profit institutions do not appear to receive any state and local funding, and private nonprofit institutions receive very little state and local funding.</p>
</section>
<section id="interesting-relationship-visual" class="level3">
<h3 class="anchored" data-anchor-id="interesting-relationship-visual">Interesting Relationship Visual</h3>
<p>It was a helpful learning exercise to try and create similar income graphs like on the IPEDS site, and I felt like all were somewhat confusing or misleading because each institutional control type really can’t be compared to each other because they label funding sources differently. For an interesting relationship visual, I decided to create a funding source by control of institution that tried to separate out these categories better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>income_graph <span class="ot">&lt;-</span> main_df <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(federal_income, state_income, local_income, tuition_income, private_income, sales_income, total_enrollment, college_type, full_time_enrollment) <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fte =</span> <span class="fu">round</span>(</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>    full_time_enrollment <span class="sc">+</span> ((total_enrollment <span class="sc">-</span> full_time_enrollment) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>),</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">contains</span>(<span class="st">"income"</span>),  <span class="sc">~</span> .x <span class="sc">/</span> fte),</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">program_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"For-Profit"</span>, college_type) <span class="sc">~</span> <span class="st">"Private for-profit"</span>,</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Private NP"</span>, college_type) <span class="sc">~</span> <span class="st">"Private nonprofit"</span>,</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Public"</span>, college_type) <span class="sc">~</span> <span class="st">"Public"</span>,</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Error"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(federal_income, state_income, local_income, tuition_income, private_income, sales_income, program_type) <span class="sc">%&gt;%</span></span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state_and_local_income =</span> state_income <span class="sc">+</span> local_income,</span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">private_and_sales_income =</span> private_income <span class="sc">+</span> sales_income) <span class="sc">%&gt;%</span></span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb87-16"><a href="#cb87-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="st">"Federal"</span> <span class="ot">=</span> <span class="fu">median</span>(federal_income), </span>
<span id="cb87-17"><a href="#cb87-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"State and Local"</span> <span class="ot">=</span> <span class="fu">median</span>(state_and_local_income),</span>
<span id="cb87-18"><a href="#cb87-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Tuition and Fees"</span> <span class="ot">=</span> <span class="fu">median</span>(tuition_income),</span>
<span id="cb87-19"><a href="#cb87-19" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Private and Sales"</span> <span class="ot">=</span> <span class="fu">median</span>(private_and_sales_income)) <span class="sc">%&gt;%</span></span>
<span id="cb87-20"><a href="#cb87-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">"Federal"</span>, <span class="st">"State and Local"</span>, <span class="st">"Tuition and Fees"</span>,</span>
<span id="cb87-21"><a href="#cb87-21" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Private and Sales"</span>), <span class="at">names_to =</span> <span class="st">"source"</span>, <span class="at">values_to =</span> <span class="st">"avg_amount"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-22"><a href="#cb87-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type, source) <span class="sc">%&gt;%</span></span>
<span id="cb87-23"><a href="#cb87-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">sum</span>(avg_amount)) <span class="sc">%&gt;%</span></span>
<span id="cb87-24"><a href="#cb87-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(program_type) <span class="sc">%&gt;%</span></span>
<span id="cb87-25"><a href="#cb87-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> total <span class="sc">/</span> <span class="fu">sum</span>(total)) <span class="sc">%&gt;%</span></span>
<span id="cb87-26"><a href="#cb87-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(source, total, <span class="at">fill =</span> <span class="fu">factor</span>(program_type))) <span class="sc">+</span></span>
<span id="cb87-27"><a href="#cb87-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb87-28"><a href="#cb87-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Median Income per Full-Time Equivalent (FTE) Student by Institution Type"</span>) <span class="sc">+</span></span>
<span id="cb87-29"><a href="#cb87-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"Funding Source"</span>) <span class="sc">+</span></span>
<span id="cb87-30"><a href="#cb87-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"Income"</span>) <span class="sc">+</span></span>
<span id="cb87-31"><a href="#cb87-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">sprintf</span>(<span class="st">"%1.1f"</span>, percent<span class="sc">*</span><span class="dv">100</span>),<span class="st">"%"</span>)),</span>
<span id="cb87-32"><a href="#cb87-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb87-33"><a href="#cb87-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb87-34"><a href="#cb87-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(program_type)) <span class="sc">+</span></span>
<span id="cb87-35"><a href="#cb87-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">angle =</span> <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb87-36"><a href="#cb87-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>() <span class="sc">+</span></span>
<span id="cb87-37"><a href="#cb87-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb87-38"><a href="#cb87-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb87-39"><a href="#cb87-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'program_type'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>income_graph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week_4_assignment_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"income_graph.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
<p>I think this visualization does a better job of separating out income for each institution, however, there is still room for improvement. I’m not sure yet what is the best way to handle the duplicative x labels (tried a few methods and underneath slanted seems to be best), and I’d like to add clearer breaks between the graphs.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>